name: Идея
description: Предложить улучшение
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую задачу решаем
      description: Что сейчас неудобно или занимает время
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Как это могло бы работать
